server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # รองรับ Vue Router (history mode) - ให้ทุก path ที่ไม่ตรงไฟล์ ส่งไปที่ index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}
